/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pandadoc.client.models.ContentLibraryItemResponseCreatedBy;
import com.pandadoc.client.models.PricingTablesResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ContentLibraryItemResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ContentLibraryItemResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DATE_CREATED = "date_created";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED)
  private String dateCreated;

  public static final String SERIALIZED_NAME_DATE_MODIFIED = "date_modified";
  @SerializedName(SERIALIZED_NAME_DATE_MODIFIED)
  private String dateModified;

  public static final String SERIALIZED_NAME_CREATED_BY = "created_by";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private ContentLibraryItemResponseCreatedBy createdBy;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Object metadata;

  public static final String SERIALIZED_NAME_TOKENS = "tokens";
  @SerializedName(SERIALIZED_NAME_TOKENS)
  private List<Object> tokens = null;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<Object> fields = null;

  public static final String SERIALIZED_NAME_PRICING = "pricing";
  @SerializedName(SERIALIZED_NAME_PRICING)
  private PricingTablesResponse pricing;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<String> tags = null;

  public static final String SERIALIZED_NAME_ROLES = "roles";
  @SerializedName(SERIALIZED_NAME_ROLES)
  private List<Object> roles = null;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_CONTENT_PLACEHOLDERS = "content_placeholders";
  @SerializedName(SERIALIZED_NAME_CONTENT_PLACEHOLDERS)
  private List<Object> contentPlaceholders = null;

  public static final String SERIALIZED_NAME_IMAGES = "images";
  @SerializedName(SERIALIZED_NAME_IMAGES)
  private List<Object> images = null;


  public ContentLibraryItemResponse id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "9d9k7VtSQ5KCXfsUQv4GxE", value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ContentLibraryItemResponse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Sample Pricing Table", value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ContentLibraryItemResponse dateCreated(String dateCreated) {
    
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2021-08-11T14:12:20.017074Z", value = "")

  public String getDateCreated() {
    return dateCreated;
  }


  public void setDateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
  }


  public ContentLibraryItemResponse dateModified(String dateModified) {
    
    this.dateModified = dateModified;
    return this;
  }

   /**
   * Get dateModified
   * @return dateModified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2021-08-11T14:13:38.562290Z", value = "")

  public String getDateModified() {
    return dateModified;
  }


  public void setDateModified(String dateModified) {
    this.dateModified = dateModified;
  }


  public ContentLibraryItemResponse createdBy(ContentLibraryItemResponseCreatedBy createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ContentLibraryItemResponseCreatedBy getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(ContentLibraryItemResponseCreatedBy createdBy) {
    this.createdBy = createdBy;
  }


  public ContentLibraryItemResponse metadata(Object metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getMetadata() {
    return metadata;
  }


  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }


  public ContentLibraryItemResponse tokens(List<Object> tokens) {
    
    this.tokens = tokens;
    return this;
  }

  public ContentLibraryItemResponse addTokensItem(Object tokensItem) {
    if (this.tokens == null) {
      this.tokens = new ArrayList<>();
    }
    this.tokens.add(tokensItem);
    return this;
  }

   /**
   * Get tokens
   * @return tokens
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getTokens() {
    return tokens;
  }


  public void setTokens(List<Object> tokens) {
    this.tokens = tokens;
  }


  public ContentLibraryItemResponse fields(List<Object> fields) {
    
    this.fields = fields;
    return this;
  }

  public ContentLibraryItemResponse addFieldsItem(Object fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getFields() {
    return fields;
  }


  public void setFields(List<Object> fields) {
    this.fields = fields;
  }


  public ContentLibraryItemResponse pricing(PricingTablesResponse pricing) {
    
    this.pricing = pricing;
    return this;
  }

   /**
   * Get pricing
   * @return pricing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PricingTablesResponse getPricing() {
    return pricing;
  }


  public void setPricing(PricingTablesResponse pricing) {
    this.pricing = pricing;
  }


  public ContentLibraryItemResponse tags(List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public ContentLibraryItemResponse addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTags() {
    return tags;
  }


  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  public ContentLibraryItemResponse roles(List<Object> roles) {
    
    this.roles = roles;
    return this;
  }

  public ContentLibraryItemResponse addRolesItem(Object rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getRoles() {
    return roles;
  }


  public void setRoles(List<Object> roles) {
    this.roles = roles;
  }


  public ContentLibraryItemResponse version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2", value = "")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public ContentLibraryItemResponse contentPlaceholders(List<Object> contentPlaceholders) {
    
    this.contentPlaceholders = contentPlaceholders;
    return this;
  }

  public ContentLibraryItemResponse addContentPlaceholdersItem(Object contentPlaceholdersItem) {
    if (this.contentPlaceholders == null) {
      this.contentPlaceholders = new ArrayList<>();
    }
    this.contentPlaceholders.add(contentPlaceholdersItem);
    return this;
  }

   /**
   * Get contentPlaceholders
   * @return contentPlaceholders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getContentPlaceholders() {
    return contentPlaceholders;
  }


  public void setContentPlaceholders(List<Object> contentPlaceholders) {
    this.contentPlaceholders = contentPlaceholders;
  }


  public ContentLibraryItemResponse images(List<Object> images) {
    
    this.images = images;
    return this;
  }

  public ContentLibraryItemResponse addImagesItem(Object imagesItem) {
    if (this.images == null) {
      this.images = new ArrayList<>();
    }
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getImages() {
    return images;
  }


  public void setImages(List<Object> images) {
    this.images = images;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentLibraryItemResponse contentLibraryItemResponse = (ContentLibraryItemResponse) o;
    return Objects.equals(this.id, contentLibraryItemResponse.id) &&
        Objects.equals(this.name, contentLibraryItemResponse.name) &&
        Objects.equals(this.dateCreated, contentLibraryItemResponse.dateCreated) &&
        Objects.equals(this.dateModified, contentLibraryItemResponse.dateModified) &&
        Objects.equals(this.createdBy, contentLibraryItemResponse.createdBy) &&
        Objects.equals(this.metadata, contentLibraryItemResponse.metadata) &&
        Objects.equals(this.tokens, contentLibraryItemResponse.tokens) &&
        Objects.equals(this.fields, contentLibraryItemResponse.fields) &&
        Objects.equals(this.pricing, contentLibraryItemResponse.pricing) &&
        Objects.equals(this.tags, contentLibraryItemResponse.tags) &&
        Objects.equals(this.roles, contentLibraryItemResponse.roles) &&
        Objects.equals(this.version, contentLibraryItemResponse.version) &&
        Objects.equals(this.contentPlaceholders, contentLibraryItemResponse.contentPlaceholders) &&
        Objects.equals(this.images, contentLibraryItemResponse.images);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, dateCreated, dateModified, createdBy, metadata, tokens, fields, pricing, tags, roles, version, contentPlaceholders, images);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentLibraryItemResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateModified: ").append(toIndentedString(dateModified)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    pricing: ").append(toIndentedString(pricing)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    contentPlaceholders: ").append(toIndentedString(contentPlaceholders)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

