/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Forwarding settings
 */
@ApiModel(description = "Forwarding settings")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DocumentSendRequestForwardingSettings {
  public static final String SERIALIZED_NAME_FORWARDING_ALLOWED = "forwarding_allowed";
  @SerializedName(SERIALIZED_NAME_FORWARDING_ALLOWED)
  private Boolean forwardingAllowed;

  public static final String SERIALIZED_NAME_FORWARDING_WITH_REASSIGNING_ALLOWED = "forwarding_with_reassigning_allowed";
  @SerializedName(SERIALIZED_NAME_FORWARDING_WITH_REASSIGNING_ALLOWED)
  private Boolean forwardingWithReassigningAllowed;

  public DocumentSendRequestForwardingSettings() { 
  }

  public DocumentSendRequestForwardingSettings forwardingAllowed(Boolean forwardingAllowed) {
    
    this.forwardingAllowed = forwardingAllowed;
    return this;
  }

   /**
   * Allow forwarding
   * @return forwardingAllowed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Allow forwarding")

  public Boolean getForwardingAllowed() {
    return forwardingAllowed;
  }


  public void setForwardingAllowed(Boolean forwardingAllowed) {
    this.forwardingAllowed = forwardingAllowed;
  }


  public DocumentSendRequestForwardingSettings forwardingWithReassigningAllowed(Boolean forwardingWithReassigningAllowed) {
    
    this.forwardingWithReassigningAllowed = forwardingWithReassigningAllowed;
    return this;
  }

   /**
   * Allow forwarding with reassigning
   * @return forwardingWithReassigningAllowed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Allow forwarding with reassigning")

  public Boolean getForwardingWithReassigningAllowed() {
    return forwardingWithReassigningAllowed;
  }


  public void setForwardingWithReassigningAllowed(Boolean forwardingWithReassigningAllowed) {
    this.forwardingWithReassigningAllowed = forwardingWithReassigningAllowed;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentSendRequestForwardingSettings documentSendRequestForwardingSettings = (DocumentSendRequestForwardingSettings) o;
    return Objects.equals(this.forwardingAllowed, documentSendRequestForwardingSettings.forwardingAllowed) &&
        Objects.equals(this.forwardingWithReassigningAllowed, documentSendRequestForwardingSettings.forwardingWithReassigningAllowed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(forwardingAllowed, forwardingWithReassigningAllowed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentSendRequestForwardingSettings {\n");
    sb.append("    forwardingAllowed: ").append(toIndentedString(forwardingAllowed)).append("\n");
    sb.append("    forwardingWithReassigningAllowed: ").append(toIndentedString(forwardingWithReassigningAllowed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

