/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pandadoc.client.models.DocumentDetailsResponseCreatedBy;
import com.pandadoc.client.models.DocumentDetailsResponseGrandTotal;
import com.pandadoc.client.models.DocumentDetailsResponseLinkedObjects;
import com.pandadoc.client.models.DocumentDetailsResponseRecipients;
import com.pandadoc.client.models.DocumentDetailsResponseTemplate;
import com.pandadoc.client.models.PricingTablesResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DocumentDetailsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DocumentDetailsResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_AUTONUMBERING_SEQUENCE_NAME_PREFIX = "autonumbering_sequence_name_prefix";
  @SerializedName(SERIALIZED_NAME_AUTONUMBERING_SEQUENCE_NAME_PREFIX)
  private Object autonumberingSequenceNamePrefix = null;

  public static final String SERIALIZED_NAME_DATE_CREATED = "date_created";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED)
  private String dateCreated;

  public static final String SERIALIZED_NAME_DATE_MODIFIED = "date_modified";
  @SerializedName(SERIALIZED_NAME_DATE_MODIFIED)
  private String dateModified;

  public static final String SERIALIZED_NAME_DATE_COMPLETED = "date_completed";
  @SerializedName(SERIALIZED_NAME_DATE_COMPLETED)
  private String dateCompleted;

  public static final String SERIALIZED_NAME_CREATED_BY = "created_by";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private DocumentDetailsResponseCreatedBy createdBy;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private DocumentDetailsResponseTemplate template;

  public static final String SERIALIZED_NAME_EXPIRATION_DATE = "expiration_date";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_DATE)
  private Object expirationDate = null;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Object metadata;

  public static final String SERIALIZED_NAME_TOKENS = "tokens";
  @SerializedName(SERIALIZED_NAME_TOKENS)
  private List<Object> tokens = null;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<Object> fields = null;

  public static final String SERIALIZED_NAME_PRICING = "pricing";
  @SerializedName(SERIALIZED_NAME_PRICING)
  private PricingTablesResponse pricing;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<String> tags = null;

  public static final String SERIALIZED_NAME_SENT_BY = "sent_by";
  @SerializedName(SERIALIZED_NAME_SENT_BY)
  private Object sentBy = null;

  public static final String SERIALIZED_NAME_RECIPIENTS = "recipients";
  @SerializedName(SERIALIZED_NAME_RECIPIENTS)
  private List<DocumentDetailsResponseRecipients> recipients = null;

  public static final String SERIALIZED_NAME_GRAND_TOTAL = "grand_total";
  @SerializedName(SERIALIZED_NAME_GRAND_TOTAL)
  private DocumentDetailsResponseGrandTotal grandTotal;

  public static final String SERIALIZED_NAME_LINKED_OBJECTS = "linked_objects";
  @SerializedName(SERIALIZED_NAME_LINKED_OBJECTS)
  private List<DocumentDetailsResponseLinkedObjects> linkedObjects = null;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;


  public DocumentDetailsResponse id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7kqXgjFejB2toXxjcC5jfZ", value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public DocumentDetailsResponse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "API Sample Document from PandaDoc Template", value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public DocumentDetailsResponse autonumberingSequenceNamePrefix(Object autonumberingSequenceNamePrefix) {
    
    this.autonumberingSequenceNamePrefix = autonumberingSequenceNamePrefix;
    return this;
  }

   /**
   * Get autonumberingSequenceNamePrefix
   * @return autonumberingSequenceNamePrefix
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAutonumberingSequenceNamePrefix() {
    return autonumberingSequenceNamePrefix;
  }


  public void setAutonumberingSequenceNamePrefix(Object autonumberingSequenceNamePrefix) {
    this.autonumberingSequenceNamePrefix = autonumberingSequenceNamePrefix;
  }


  public DocumentDetailsResponse dateCreated(String dateCreated) {
    
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2021-10-23T21:07:04.147Z", value = "")

  public String getDateCreated() {
    return dateCreated;
  }


  public void setDateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
  }


  public DocumentDetailsResponse dateModified(String dateModified) {
    
    this.dateModified = dateModified;
    return this;
  }

   /**
   * Get dateModified
   * @return dateModified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2021-10-23T21:07:04.147Z", value = "")

  public String getDateModified() {
    return dateModified;
  }


  public void setDateModified(String dateModified) {
    this.dateModified = dateModified;
  }


  public DocumentDetailsResponse dateCompleted(String dateCompleted) {
    
    this.dateCompleted = dateCompleted;
    return this;
  }

   /**
   * Get dateCompleted
   * @return dateCompleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2021-10-23T21:07:04.147Z", value = "")

  public String getDateCompleted() {
    return dateCompleted;
  }


  public void setDateCompleted(String dateCompleted) {
    this.dateCompleted = dateCompleted;
  }


  public DocumentDetailsResponse createdBy(DocumentDetailsResponseCreatedBy createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DocumentDetailsResponseCreatedBy getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(DocumentDetailsResponseCreatedBy createdBy) {
    this.createdBy = createdBy;
  }


  public DocumentDetailsResponse template(DocumentDetailsResponseTemplate template) {
    
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DocumentDetailsResponseTemplate getTemplate() {
    return template;
  }


  public void setTemplate(DocumentDetailsResponseTemplate template) {
    this.template = template;
  }


  public DocumentDetailsResponse expirationDate(Object expirationDate) {
    
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getExpirationDate() {
    return expirationDate;
  }


  public void setExpirationDate(Object expirationDate) {
    this.expirationDate = expirationDate;
  }


  public DocumentDetailsResponse metadata(Object metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"document__created_via_public_api\":\"true\",\"my_favorite_pet\":\"Panda\",\"opp_id\":\"1234567\"}", value = "")

  public Object getMetadata() {
    return metadata;
  }


  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }


  public DocumentDetailsResponse tokens(List<Object> tokens) {
    
    this.tokens = tokens;
    return this;
  }

  public DocumentDetailsResponse addTokensItem(Object tokensItem) {
    if (this.tokens == null) {
      this.tokens = new ArrayList<>();
    }
    this.tokens.add(tokensItem);
    return this;
  }

   /**
   * Get tokens
   * @return tokens
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"name\":\"Document.GrandTotal\",\"value\":\"$29.99\"},{\"name\":\"Favorite.Pet\",\"value\":\"Panda\"}]", value = "")

  public List<Object> getTokens() {
    return tokens;
  }


  public void setTokens(List<Object> tokens) {
    this.tokens = tokens;
  }


  public DocumentDetailsResponse fields(List<Object> fields) {
    
    this.fields = fields;
    return this;
  }

  public DocumentDetailsResponse addFieldsItem(Object fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"uuid\":\"f9574c3b-5b1e-4479-b2c9-c3ccd92748f3\",\"name\":\"Click to upload a file\",\"title\":\"\",\"placeholder\":\"Click to upload a file\",\"value\":{\"name\":\"file_name.pdf\",\"url\":\"https://uploadfields.pandadoc-static.com/collect_files/e7b082c2-395b-43c7-a24c-66bd1bbb5d2f/65af1f23-9d26-4622-8ff0-f406b3be27b8-file_name.pdf\"},\"assigned_to\":{\"id\":\"Fx7CgaVgpGbJBgZ4i5oTx8\",\"first_name\":\"John\",\"last_name\":\"Roe\",\"email\":\"john@example.com\",\"recipient_type\":\"signer\",\"has_completed\":false,\"role\":\"\",\"type\":\"recipient\"}},{\"uuid\":\"eyGJgkWJfUpRtUCsCFDwGU\",\"name\":\"Favorite.Color\",\"merge_field\":\"Favorite.Color\",\"title\":\"Textfield\",\"value\":\"value\",\"assigned_to\":{\"id\":\"Fx7CgaVgpGbJBgZ4i5oTx8\",\"first_name\":\"John\",\"last_name\":\"Roe\",\"email\":\"john@example.com\",\"recipient_type\":\"signer\",\"has_completed\":false,\"role\":\"\",\"type\":\"recipient\"}},{\"uuid\":\"M4755SJuoyz5Jzsw4WXTDb\",\"name\":\"Like\",\"merge_field\":\"Like\",\"title\":\"Checkbox\",\"value\":\"value\",\"assigned_to\":{\"id\":\"Fx7CgaVgpGbJBgZ4i5oTx8\",\"first_name\":\"John\",\"last_name\":\"Roe\",\"email\":\"john@example.com\",\"recipient_type\":\"signer\",\"has_completed\":false,\"role\":\"\",\"type\":\"recipient\"}}]", value = "")

  public List<Object> getFields() {
    return fields;
  }


  public void setFields(List<Object> fields) {
    this.fields = fields;
  }


  public DocumentDetailsResponse pricing(PricingTablesResponse pricing) {
    
    this.pricing = pricing;
    return this;
  }

   /**
   * Get pricing
   * @return pricing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PricingTablesResponse getPricing() {
    return pricing;
  }


  public void setPricing(PricingTablesResponse pricing) {
    this.pricing = pricing;
  }


  public DocumentDetailsResponse version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2", value = "")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public DocumentDetailsResponse tags(List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public DocumentDetailsResponse addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"tag1\",\"tag2\"]", value = "")

  public List<String> getTags() {
    return tags;
  }


  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  public DocumentDetailsResponse sentBy(Object sentBy) {
    
    this.sentBy = sentBy;
    return this;
  }

   /**
   * Get sentBy
   * @return sentBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getSentBy() {
    return sentBy;
  }


  public void setSentBy(Object sentBy) {
    this.sentBy = sentBy;
  }


  public DocumentDetailsResponse recipients(List<DocumentDetailsResponseRecipients> recipients) {
    
    this.recipients = recipients;
    return this;
  }

  public DocumentDetailsResponse addRecipientsItem(DocumentDetailsResponseRecipients recipientsItem) {
    if (this.recipients == null) {
      this.recipients = new ArrayList<>();
    }
    this.recipients.add(recipientsItem);
    return this;
  }

   /**
   * Get recipients
   * @return recipients
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DocumentDetailsResponseRecipients> getRecipients() {
    return recipients;
  }


  public void setRecipients(List<DocumentDetailsResponseRecipients> recipients) {
    this.recipients = recipients;
  }


  public DocumentDetailsResponse grandTotal(DocumentDetailsResponseGrandTotal grandTotal) {
    
    this.grandTotal = grandTotal;
    return this;
  }

   /**
   * Get grandTotal
   * @return grandTotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DocumentDetailsResponseGrandTotal getGrandTotal() {
    return grandTotal;
  }


  public void setGrandTotal(DocumentDetailsResponseGrandTotal grandTotal) {
    this.grandTotal = grandTotal;
  }


  public DocumentDetailsResponse linkedObjects(List<DocumentDetailsResponseLinkedObjects> linkedObjects) {
    
    this.linkedObjects = linkedObjects;
    return this;
  }

  public DocumentDetailsResponse addLinkedObjectsItem(DocumentDetailsResponseLinkedObjects linkedObjectsItem) {
    if (this.linkedObjects == null) {
      this.linkedObjects = new ArrayList<>();
    }
    this.linkedObjects.add(linkedObjectsItem);
    return this;
  }

   /**
   * Get linkedObjects
   * @return linkedObjects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DocumentDetailsResponseLinkedObjects> getLinkedObjects() {
    return linkedObjects;
  }


  public void setLinkedObjects(List<DocumentDetailsResponseLinkedObjects> linkedObjects) {
    this.linkedObjects = linkedObjects;
  }


  public DocumentDetailsResponse status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "document.draft", value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentDetailsResponse documentDetailsResponse = (DocumentDetailsResponse) o;
    return Objects.equals(this.id, documentDetailsResponse.id) &&
        Objects.equals(this.name, documentDetailsResponse.name) &&
        Objects.equals(this.autonumberingSequenceNamePrefix, documentDetailsResponse.autonumberingSequenceNamePrefix) &&
        Objects.equals(this.dateCreated, documentDetailsResponse.dateCreated) &&
        Objects.equals(this.dateModified, documentDetailsResponse.dateModified) &&
        Objects.equals(this.dateCompleted, documentDetailsResponse.dateCompleted) &&
        Objects.equals(this.createdBy, documentDetailsResponse.createdBy) &&
        Objects.equals(this.template, documentDetailsResponse.template) &&
        Objects.equals(this.expirationDate, documentDetailsResponse.expirationDate) &&
        Objects.equals(this.metadata, documentDetailsResponse.metadata) &&
        Objects.equals(this.tokens, documentDetailsResponse.tokens) &&
        Objects.equals(this.fields, documentDetailsResponse.fields) &&
        Objects.equals(this.pricing, documentDetailsResponse.pricing) &&
        Objects.equals(this.version, documentDetailsResponse.version) &&
        Objects.equals(this.tags, documentDetailsResponse.tags) &&
        Objects.equals(this.sentBy, documentDetailsResponse.sentBy) &&
        Objects.equals(this.recipients, documentDetailsResponse.recipients) &&
        Objects.equals(this.grandTotal, documentDetailsResponse.grandTotal) &&
        Objects.equals(this.linkedObjects, documentDetailsResponse.linkedObjects) &&
        Objects.equals(this.status, documentDetailsResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, autonumberingSequenceNamePrefix, dateCreated, dateModified, dateCompleted, createdBy, template, expirationDate, metadata, tokens, fields, pricing, version, tags, sentBy, recipients, grandTotal, linkedObjects, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentDetailsResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    autonumberingSequenceNamePrefix: ").append(toIndentedString(autonumberingSequenceNamePrefix)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateModified: ").append(toIndentedString(dateModified)).append("\n");
    sb.append("    dateCompleted: ").append(toIndentedString(dateCompleted)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    pricing: ").append(toIndentedString(pricing)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    sentBy: ").append(toIndentedString(sentBy)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    grandTotal: ").append(toIndentedString(grandTotal)).append("\n");
    sb.append("    linkedObjects: ").append(toIndentedString(linkedObjects)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

