/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets DocumentOrderingFieldsEnum
 */
@JsonAdapter(DocumentOrderingFieldsEnum.Adapter.class)
public enum DocumentOrderingFieldsEnum {
  
  NAME("name"),
  
  DATE_CREATED("date_created"),
  
  DATE_STATUS_CHANGED("date_status_changed"),
  
  DATE_OF_LAST_ACTION("date_of_last_action"),
  
  DATE_MODIFIED("date_modified"),
  
  DATE_SENT("date_sent"),
  
  DATE_COMPLETED("date_completed"),
  
  DATE_EXPIRATION("date_expiration"),
  
  DATE_DECLINED("date_declined"),
  
  STATUS("status"),
  
  _NAME("-name"),
  
  _DATE_CREATED("-date_created"),
  
  _DATE_STATUS_CHANGED("-date_status_changed"),
  
  _DATE_OF_LAST_ACTION("-date_of_last_action"),
  
  _DATE_MODIFIED("-date_modified"),
  
  _DATE_SENT("-date_sent"),
  
  _DATE_COMPLETED("-date_completed"),
  
  _DATE_EXPIRATION("-date_expiration"),
  
  _DATE_DECLINED("-date_declined"),
  
  _STATUS("-status");

  private String value;

  DocumentOrderingFieldsEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DocumentOrderingFieldsEnum fromValue(String value) {
    for (DocumentOrderingFieldsEnum b : DocumentOrderingFieldsEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DocumentOrderingFieldsEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final DocumentOrderingFieldsEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DocumentOrderingFieldsEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DocumentOrderingFieldsEnum.fromValue(value);
    }
  }
}

