/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets DocumentStatusEnum
 */
@JsonAdapter(DocumentStatusEnum.Adapter.class)
public enum DocumentStatusEnum {
  
  DRAFT("document.draft"),
  
  SENT("document.sent"),
  
  COMPLETED("document.completed"),
  
  UPLOADED("document.uploaded"),
  
  ERROR("document.error"),
  
  VIEWED("document.viewed"),
  
  WAITING_APPROVAL("document.waiting_approval"),
  
  APPROVED("document.approved"),
  
  REJECTED("document.rejected"),
  
  WAITING_PAY("document.waiting_pay"),
  
  PAID("document.paid"),
  
  VOIDED("document.voided"),
  
  DECLINED("document.declined"),
  
  EXTERNAL_REVIEW("document.external_review");

  private String value;

  DocumentStatusEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DocumentStatusEnum fromValue(String value) {
    for (DocumentStatusEnum b : DocumentStatusEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DocumentStatusEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final DocumentStatusEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DocumentStatusEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DocumentStatusEnum.fromValue(value);
    }
  }
}

