/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DocumentSendRequestSelectedApproversGroupAssignees
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DocumentSendRequestSelectedApproversGroupAssignees {
  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private String user;

  public static final String SERIALIZED_NAME_IS_SELECTED = "is_selected";
  @SerializedName(SERIALIZED_NAME_IS_SELECTED)
  private Boolean isSelected;

  public DocumentSendRequestSelectedApproversGroupAssignees() { 
  }

  public DocumentSendRequestSelectedApproversGroupAssignees user(String user) {
    
    this.user = user;
    return this;
  }

   /**
   * User ID
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "tpBLrk3vJoLggypMSRt92i", value = "User ID")

  public String getUser() {
    return user;
  }


  public void setUser(String user) {
    this.user = user;
  }


  public DocumentSendRequestSelectedApproversGroupAssignees isSelected(Boolean isSelected) {
    
    this.isSelected = isSelected;
    return this;
  }

   /**
   * Whether the user is selected
   * @return isSelected
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Whether the user is selected")

  public Boolean getIsSelected() {
    return isSelected;
  }


  public void setIsSelected(Boolean isSelected) {
    this.isSelected = isSelected;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentSendRequestSelectedApproversGroupAssignees documentSendRequestSelectedApproversGroupAssignees = (DocumentSendRequestSelectedApproversGroupAssignees) o;
    return Objects.equals(this.user, documentSendRequestSelectedApproversGroupAssignees.user) &&
        Objects.equals(this.isSelected, documentSendRequestSelectedApproversGroupAssignees.isSelected);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, isSelected);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentSendRequestSelectedApproversGroupAssignees {\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    isSelected: ").append(toIndentedString(isSelected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

