/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pandadoc.client.models.DocumentCreateByTemplateRequestRecipients;
import com.pandadoc.client.models.PricingTableRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DocumentCreateRequestContentLibraryItems
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DocumentCreateRequestContentLibraryItems {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_PRICING_TABLES = "pricing_tables";
  @SerializedName(SERIALIZED_NAME_PRICING_TABLES)
  private List<PricingTableRequest> pricingTables = null;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private Object fields;

  public static final String SERIALIZED_NAME_RECIPIENTS = "recipients";
  @SerializedName(SERIALIZED_NAME_RECIPIENTS)
  private List<DocumentCreateByTemplateRequestRecipients> recipients = null;


  public DocumentCreateRequestContentLibraryItems id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Content library item id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "hryJY9mqYZHjQCYQuSjRQg", required = true, value = "Content library item id")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public DocumentCreateRequestContentLibraryItems pricingTables(List<PricingTableRequest> pricingTables) {
    
    this.pricingTables = pricingTables;
    return this;
  }

  public DocumentCreateRequestContentLibraryItems addPricingTablesItem(PricingTableRequest pricingTablesItem) {
    if (this.pricingTables == null) {
      this.pricingTables = new ArrayList<>();
    }
    this.pricingTables.add(pricingTablesItem);
    return this;
  }

   /**
   * Get pricingTables
   * @return pricingTables
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<PricingTableRequest> getPricingTables() {
    return pricingTables;
  }


  public void setPricingTables(List<PricingTableRequest> pricingTables) {
    this.pricingTables = pricingTables;
  }


  public DocumentCreateRequestContentLibraryItems fields(Object fields) {
    
    this.fields = fields;
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getFields() {
    return fields;
  }


  public void setFields(Object fields) {
    this.fields = fields;
  }


  public DocumentCreateRequestContentLibraryItems recipients(List<DocumentCreateByTemplateRequestRecipients> recipients) {
    
    this.recipients = recipients;
    return this;
  }

  public DocumentCreateRequestContentLibraryItems addRecipientsItem(DocumentCreateByTemplateRequestRecipients recipientsItem) {
    if (this.recipients == null) {
      this.recipients = new ArrayList<>();
    }
    this.recipients.add(recipientsItem);
    return this;
  }

   /**
   * Get recipients
   * @return recipients
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DocumentCreateByTemplateRequestRecipients> getRecipients() {
    return recipients;
  }


  public void setRecipients(List<DocumentCreateByTemplateRequestRecipients> recipients) {
    this.recipients = recipients;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentCreateRequestContentLibraryItems documentCreateRequestContentLibraryItems = (DocumentCreateRequestContentLibraryItems) o;
    return Objects.equals(this.id, documentCreateRequestContentLibraryItems.id) &&
        Objects.equals(this.pricingTables, documentCreateRequestContentLibraryItems.pricingTables) &&
        Objects.equals(this.fields, documentCreateRequestContentLibraryItems.fields) &&
        Objects.equals(this.recipients, documentCreateRequestContentLibraryItems.recipients);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, pricingTables, fields, recipients);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentCreateRequestContentLibraryItems {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    pricingTables: ").append(toIndentedString(pricingTables)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

