/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pandadoc.client.models.LinkedObjectCreateResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LinkedObjectListResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LinkedObjectListResponse {
  public static final String SERIALIZED_NAME_LINKED_OBJECTS = "linked_objects";
  @SerializedName(SERIALIZED_NAME_LINKED_OBJECTS)
  private List<LinkedObjectCreateResponse> linkedObjects = null;


  public LinkedObjectListResponse linkedObjects(List<LinkedObjectCreateResponse> linkedObjects) {
    
    this.linkedObjects = linkedObjects;
    return this;
  }

  public LinkedObjectListResponse addLinkedObjectsItem(LinkedObjectCreateResponse linkedObjectsItem) {
    if (this.linkedObjects == null) {
      this.linkedObjects = new ArrayList<>();
    }
    this.linkedObjects.add(linkedObjectsItem);
    return this;
  }

   /**
   * Get linkedObjects
   * @return linkedObjects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<LinkedObjectCreateResponse> getLinkedObjects() {
    return linkedObjects;
  }


  public void setLinkedObjects(List<LinkedObjectCreateResponse> linkedObjects) {
    this.linkedObjects = linkedObjects;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkedObjectListResponse linkedObjectListResponse = (LinkedObjectListResponse) o;
    return Objects.equals(this.linkedObjects, linkedObjectListResponse.linkedObjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkedObjects);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkedObjectListResponse {\n");
    sb.append("    linkedObjects: ").append(toIndentedString(linkedObjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

