/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pandadoc.client.models.PricingTableRequestOptionsDiscount;
import com.pandadoc.client.models.PricingTableRequestOptionsTaxFirst;
import com.pandadoc.client.models.PricingTableRequestOptionsTaxSecond;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PricingTableRequestOptions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PricingTableRequestOptions {
  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_DISCOUNT = "discount";
  @SerializedName(SERIALIZED_NAME_DISCOUNT)
  private PricingTableRequestOptionsDiscount discount;

  public static final String SERIALIZED_NAME_TAX_FIRST = "tax_first";
  @SerializedName(SERIALIZED_NAME_TAX_FIRST)
  private PricingTableRequestOptionsTaxFirst taxFirst;

  public static final String SERIALIZED_NAME_TAX_SECOND = "tax_second";
  @SerializedName(SERIALIZED_NAME_TAX_SECOND)
  private PricingTableRequestOptionsTaxSecond taxSecond;

  public PricingTableRequestOptions() { 
  }

  public PricingTableRequestOptions currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "USD", value = "")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public PricingTableRequestOptions discount(PricingTableRequestOptionsDiscount discount) {
    
    this.discount = discount;
    return this;
  }

   /**
   * Get discount
   * @return discount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PricingTableRequestOptionsDiscount getDiscount() {
    return discount;
  }


  public void setDiscount(PricingTableRequestOptionsDiscount discount) {
    this.discount = discount;
  }


  public PricingTableRequestOptions taxFirst(PricingTableRequestOptionsTaxFirst taxFirst) {
    
    this.taxFirst = taxFirst;
    return this;
  }

   /**
   * Get taxFirst
   * @return taxFirst
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PricingTableRequestOptionsTaxFirst getTaxFirst() {
    return taxFirst;
  }


  public void setTaxFirst(PricingTableRequestOptionsTaxFirst taxFirst) {
    this.taxFirst = taxFirst;
  }


  public PricingTableRequestOptions taxSecond(PricingTableRequestOptionsTaxSecond taxSecond) {
    
    this.taxSecond = taxSecond;
    return this;
  }

   /**
   * Get taxSecond
   * @return taxSecond
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PricingTableRequestOptionsTaxSecond getTaxSecond() {
    return taxSecond;
  }


  public void setTaxSecond(PricingTableRequestOptionsTaxSecond taxSecond) {
    this.taxSecond = taxSecond;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricingTableRequestOptions pricingTableRequestOptions = (PricingTableRequestOptions) o;
    return Objects.equals(this.currency, pricingTableRequestOptions.currency) &&
        Objects.equals(this.discount, pricingTableRequestOptions.discount) &&
        Objects.equals(this.taxFirst, pricingTableRequestOptions.taxFirst) &&
        Objects.equals(this.taxSecond, pricingTableRequestOptions.taxSecond);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, discount, taxFirst, taxSecond);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricingTableRequestOptions {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    taxFirst: ").append(toIndentedString(taxFirst)).append("\n");
    sb.append("    taxSecond: ").append(toIndentedString(taxSecond)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

