/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pandadoc.client.models.PricingTableRequestOptions;
import com.pandadoc.client.models.PricingTableRequestSections;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PricingTableRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PricingTableRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DATA_MERGE = "data_merge";
  @SerializedName(SERIALIZED_NAME_DATA_MERGE)
  private Boolean dataMerge;

  public static final String SERIALIZED_NAME_OPTIONS = "options";
  @SerializedName(SERIALIZED_NAME_OPTIONS)
  private PricingTableRequestOptions options;

  public static final String SERIALIZED_NAME_SECTIONS = "sections";
  @SerializedName(SERIALIZED_NAME_SECTIONS)
  private List<PricingTableRequestSections> sections = null;


  public PricingTableRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Pricing Table 1", value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public PricingTableRequest dataMerge(Boolean dataMerge) {
    
    this.dataMerge = dataMerge;
    return this;
  }

   /**
   * When set to true all field names in data rows must be passed as external names defined in the template.
   * @return dataMerge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When set to true all field names in data rows must be passed as external names defined in the template.")

  public Boolean getDataMerge() {
    return dataMerge;
  }


  public void setDataMerge(Boolean dataMerge) {
    this.dataMerge = dataMerge;
  }


  public PricingTableRequest options(PricingTableRequestOptions options) {
    
    this.options = options;
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PricingTableRequestOptions getOptions() {
    return options;
  }


  public void setOptions(PricingTableRequestOptions options) {
    this.options = options;
  }


  public PricingTableRequest sections(List<PricingTableRequestSections> sections) {
    
    this.sections = sections;
    return this;
  }

  public PricingTableRequest addSectionsItem(PricingTableRequestSections sectionsItem) {
    if (this.sections == null) {
      this.sections = new ArrayList<>();
    }
    this.sections.add(sectionsItem);
    return this;
  }

   /**
   * Get sections
   * @return sections
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<PricingTableRequestSections> getSections() {
    return sections;
  }


  public void setSections(List<PricingTableRequestSections> sections) {
    this.sections = sections;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricingTableRequest pricingTableRequest = (PricingTableRequest) o;
    return Objects.equals(this.name, pricingTableRequest.name) &&
        Objects.equals(this.dataMerge, pricingTableRequest.dataMerge) &&
        Objects.equals(this.options, pricingTableRequest.options) &&
        Objects.equals(this.sections, pricingTableRequest.sections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, dataMerge, options, sections);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricingTableRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dataMerge: ").append(toIndentedString(dataMerge)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    sections: ").append(toIndentedString(sections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

