/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pandadoc.client.models.QuoteResponseSectionColumn;
import com.pandadoc.client.models.QuoteResponseSectionItem;
import com.pandadoc.client.models.QuoteResponseSectionSummary;
import com.pandadoc.client.models.QuoteSectionSettings;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * QuoteResponseSections
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class QuoteResponseSections {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  private QuoteResponseSectionSummary summary;

  public static final String SERIALIZED_NAME_COLUMNS = "columns";
  @SerializedName(SERIALIZED_NAME_COLUMNS)
  private List<QuoteResponseSectionColumn> columns = null;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<QuoteResponseSectionItem> items = null;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private String total;

  public static final String SERIALIZED_NAME_SETTINGS = "settings";
  @SerializedName(SERIALIZED_NAME_SETTINGS)
  private QuoteSectionSettings settings;

  public QuoteResponseSections() { 
  }

  public QuoteResponseSections id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public QuoteResponseSections name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public QuoteResponseSections summary(QuoteResponseSectionSummary summary) {
    
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public QuoteResponseSectionSummary getSummary() {
    return summary;
  }


  public void setSummary(QuoteResponseSectionSummary summary) {
    this.summary = summary;
  }


  public QuoteResponseSections columns(List<QuoteResponseSectionColumn> columns) {
    
    this.columns = columns;
    return this;
  }

  public QuoteResponseSections addColumnsItem(QuoteResponseSectionColumn columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<>();
    }
    this.columns.add(columnsItem);
    return this;
  }

   /**
   * Get columns
   * @return columns
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<QuoteResponseSectionColumn> getColumns() {
    return columns;
  }


  public void setColumns(List<QuoteResponseSectionColumn> columns) {
    this.columns = columns;
  }


  public QuoteResponseSections items(List<QuoteResponseSectionItem> items) {
    
    this.items = items;
    return this;
  }

  public QuoteResponseSections addItemsItem(QuoteResponseSectionItem itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<QuoteResponseSectionItem> getItems() {
    return items;
  }


  public void setItems(List<QuoteResponseSectionItem> items) {
    this.items = items;
  }


  public QuoteResponseSections total(String total) {
    
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1000", value = "")

  public String getTotal() {
    return total;
  }


  public void setTotal(String total) {
    this.total = total;
  }


  public QuoteResponseSections settings(QuoteSectionSettings settings) {
    
    this.settings = settings;
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public QuoteSectionSettings getSettings() {
    return settings;
  }


  public void setSettings(QuoteSectionSettings settings) {
    this.settings = settings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteResponseSections quoteResponseSections = (QuoteResponseSections) o;
    return Objects.equals(this.id, quoteResponseSections.id) &&
        Objects.equals(this.name, quoteResponseSections.name) &&
        Objects.equals(this.summary, quoteResponseSections.summary) &&
        Objects.equals(this.columns, quoteResponseSections.columns) &&
        Objects.equals(this.items, quoteResponseSections.items) &&
        Objects.equals(this.total, quoteResponseSections.total) &&
        Objects.equals(this.settings, quoteResponseSections.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, summary, columns, items, total, settings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteResponseSections {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

