/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * QuoteUpdateRequestPriceSettingsTiers
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class QuoteUpdateRequestPriceSettingsTiers {
  public static final String SERIALIZED_NAME_MIN_QTY = "min_qty";
  @SerializedName(SERIALIZED_NAME_MIN_QTY)
  private Integer minQty;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private BigDecimal value;

  public QuoteUpdateRequestPriceSettingsTiers() { 
  }

  public QuoteUpdateRequestPriceSettingsTiers minQty(Integer minQty) {
    
    this.minQty = minQty;
    return this;
  }

   /**
   * Get minQty
   * @return minQty
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getMinQty() {
    return minQty;
  }


  public void setMinQty(Integer minQty) {
    this.minQty = minQty;
  }


  public QuoteUpdateRequestPriceSettingsTiers value(BigDecimal value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getValue() {
    return value;
  }


  public void setValue(BigDecimal value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteUpdateRequestPriceSettingsTiers quoteUpdateRequestPriceSettingsTiers = (QuoteUpdateRequestPriceSettingsTiers) o;
    return Objects.equals(this.minQty, quoteUpdateRequestPriceSettingsTiers.minQty) &&
        Objects.equals(this.value, quoteUpdateRequestPriceSettingsTiers.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minQty, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteUpdateRequestPriceSettingsTiers {\n");
    sb.append("    minQty: ").append(toIndentedString(minQty)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

