/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TemplatesFolderCreateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TemplatesFolderCreateRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PARENT_UUID = "parent_uuid";
  @SerializedName(SERIALIZED_NAME_PARENT_UUID)
  private String parentUuid;

  public TemplatesFolderCreateRequest() { 
  }

  public TemplatesFolderCreateRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name the folder for Templates you are creating.
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "A new template folder", required = true, value = "Name the folder for Templates you are creating.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public TemplatesFolderCreateRequest parentUuid(String parentUuid) {
    
    this.parentUuid = parentUuid;
    return this;
  }

   /**
   * ID of the parent folder. To create a new folder in the root folder, remove this parameter in the request.
   * @return parentUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Nq8htXxFssmhRxAPSP4SBP", value = "ID of the parent folder. To create a new folder in the root folder, remove this parameter in the request.")

  public String getParentUuid() {
    return parentUuid;
  }


  public void setParentUuid(String parentUuid) {
    this.parentUuid = parentUuid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplatesFolderCreateRequest templatesFolderCreateRequest = (TemplatesFolderCreateRequest) o;
    return Objects.equals(this.name, templatesFolderCreateRequest.name) &&
        Objects.equals(this.parentUuid, templatesFolderCreateRequest.parentUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, parentUuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplatesFolderCreateRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentUuid: ").append(toIndentedString(parentUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

