/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pandadoc.client.models.TemplateDetailsResponsePreassignedPerson;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TemplateDetailsResponseRoles
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TemplateDetailsResponseRoles {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SIGNING_ORDER = "signing_order";
  @SerializedName(SERIALIZED_NAME_SIGNING_ORDER)
  private String signingOrder;

  public static final String SERIALIZED_NAME_PREASSIGNED_PERSON = "preassigned_person";
  @SerializedName(SERIALIZED_NAME_PREASSIGNED_PERSON)
  private TemplateDetailsResponsePreassignedPerson preassignedPerson;

  public TemplateDetailsResponseRoles() { 
  }

  public TemplateDetailsResponseRoles id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "HHaFsYvJCqMvdAtXwGcyLn", value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public TemplateDetailsResponseRoles name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Sender", value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public TemplateDetailsResponseRoles signingOrder(String signingOrder) {
    
    this.signingOrder = signingOrder;
    return this;
  }

   /**
   * Get signingOrder
   * @return signingOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSigningOrder() {
    return signingOrder;
  }


  public void setSigningOrder(String signingOrder) {
    this.signingOrder = signingOrder;
  }


  public TemplateDetailsResponseRoles preassignedPerson(TemplateDetailsResponsePreassignedPerson preassignedPerson) {
    
    this.preassignedPerson = preassignedPerson;
    return this;
  }

   /**
   * Get preassignedPerson
   * @return preassignedPerson
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TemplateDetailsResponsePreassignedPerson getPreassignedPerson() {
    return preassignedPerson;
  }


  public void setPreassignedPerson(TemplateDetailsResponsePreassignedPerson preassignedPerson) {
    this.preassignedPerson = preassignedPerson;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateDetailsResponseRoles templateDetailsResponseRoles = (TemplateDetailsResponseRoles) o;
    return Objects.equals(this.id, templateDetailsResponseRoles.id) &&
        Objects.equals(this.name, templateDetailsResponseRoles.name) &&
        Objects.equals(this.signingOrder, templateDetailsResponseRoles.signingOrder) &&
        Objects.equals(this.preassignedPerson, templateDetailsResponseRoles.preassignedPerson);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, signingOrder, preassignedPerson);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateDetailsResponseRoles {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    signingOrder: ").append(toIndentedString(signingOrder)).append("\n");
    sb.append("    preassignedPerson: ").append(toIndentedString(preassignedPerson)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

