/*
 * PandaDoc Public API
 * PandaDoc Public API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pandadoc.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pandadoc.client.models.WebhookEventErrorEnum;
import com.pandadoc.client.models.WebhookEventTriggerEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * WebhookEventDetailsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WebhookEventDetailsResponse {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private UUID uuid;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private WebhookEventTriggerEnum type;

  public static final String SERIALIZED_NAME_HTTP_STATUS_CODE = "http_status_code";
  @SerializedName(SERIALIZED_NAME_HTTP_STATUS_CODE)
  private Integer httpStatusCode;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private WebhookEventErrorEnum error;

  public static final String SERIALIZED_NAME_DELIVERY_TIME = "delivery_time";
  @SerializedName(SERIALIZED_NAME_DELIVERY_TIME)
  private OffsetDateTime deliveryTime;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_SIGNATURE = "signature";
  @SerializedName(SERIALIZED_NAME_SIGNATURE)
  private String signature;

  public static final String SERIALIZED_NAME_REQUEST_BODY = "request_body";
  @SerializedName(SERIALIZED_NAME_REQUEST_BODY)
  private String requestBody;

  public static final String SERIALIZED_NAME_RESPONSE_BODY = "response_body";
  @SerializedName(SERIALIZED_NAME_RESPONSE_BODY)
  private String responseBody;

  public static final String SERIALIZED_NAME_RESPONSE_HEADERS = "response_headers";
  @SerializedName(SERIALIZED_NAME_RESPONSE_HEADERS)
  private String responseHeaders;

  public static final String SERIALIZED_NAME_EVENT_TIME = "event_time";
  @SerializedName(SERIALIZED_NAME_EVENT_TIME)
  private OffsetDateTime eventTime;

  public WebhookEventDetailsResponse() { 
  }

  public WebhookEventDetailsResponse uuid(UUID uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Unique webhook subscription event identifier
   * @return uuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Unique webhook subscription event identifier")

  public UUID getUuid() {
    return uuid;
  }


  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }


  public WebhookEventDetailsResponse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Webhook subscription name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "My Subscription", value = "Webhook subscription name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public WebhookEventDetailsResponse type(WebhookEventTriggerEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WebhookEventTriggerEnum getType() {
    return type;
  }


  public void setType(WebhookEventTriggerEnum type) {
    this.type = type;
  }


  public WebhookEventDetailsResponse httpStatusCode(Integer httpStatusCode) {
    
    this.httpStatusCode = httpStatusCode;
    return this;
  }

   /**
   * Webhook subscription event response http status code
   * @return httpStatusCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "200", value = "Webhook subscription event response http status code")

  public Integer getHttpStatusCode() {
    return httpStatusCode;
  }


  public void setHttpStatusCode(Integer httpStatusCode) {
    this.httpStatusCode = httpStatusCode;
  }


  public WebhookEventDetailsResponse error(WebhookEventErrorEnum error) {
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WebhookEventErrorEnum getError() {
    return error;
  }


  public void setError(WebhookEventErrorEnum error) {
    this.error = error;
  }


  public WebhookEventDetailsResponse deliveryTime(OffsetDateTime deliveryTime) {
    
    this.deliveryTime = deliveryTime;
    return this;
  }

   /**
   * Webhook subscription event delivery time
   * @return deliveryTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-06-20T15:04:59.424730Z", value = "Webhook subscription event delivery time")

  public OffsetDateTime getDeliveryTime() {
    return deliveryTime;
  }


  public void setDeliveryTime(OffsetDateTime deliveryTime) {
    this.deliveryTime = deliveryTime;
  }


  public WebhookEventDetailsResponse url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Webhook subscription event destination url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://example.com", value = "Webhook subscription event destination url")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public WebhookEventDetailsResponse signature(String signature) {
    
    this.signature = signature;
    return this;
  }

   /**
   * Webhook subscription event digital signature
   * @return signature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "587c22285F57883db3ee", value = "Webhook subscription event digital signature")

  public String getSignature() {
    return signature;
  }


  public void setSignature(String signature) {
    this.signature = signature;
  }


  public WebhookEventDetailsResponse requestBody(String requestBody) {
    
    this.requestBody = requestBody;
    return this;
  }

   /**
   * Webhook subscription event request body
   * @return requestBody
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\\\"event\\\":\\\"document_state_changed\\\"}]", value = "Webhook subscription event request body")

  public String getRequestBody() {
    return requestBody;
  }


  public void setRequestBody(String requestBody) {
    this.requestBody = requestBody;
  }


  public WebhookEventDetailsResponse responseBody(String responseBody) {
    
    this.responseBody = responseBody;
    return this;
  }

   /**
   * Webhook subscription response body
   * @return responseBody
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "<!doctype html>\\n<html>\\n</html>", value = "Webhook subscription response body")

  public String getResponseBody() {
    return responseBody;
  }


  public void setResponseBody(String responseBody) {
    this.responseBody = responseBody;
  }


  public WebhookEventDetailsResponse responseHeaders(String responseHeaders) {
    
    this.responseHeaders = responseHeaders;
    return this;
  }

   /**
   * Webhook subscription response headers
   * @return responseHeaders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[cache-control:\\\"max-age=604800\\\"]", value = "Webhook subscription response headers")

  public String getResponseHeaders() {
    return responseHeaders;
  }


  public void setResponseHeaders(String responseHeaders) {
    this.responseHeaders = responseHeaders;
  }


  public WebhookEventDetailsResponse eventTime(OffsetDateTime eventTime) {
    
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Webhook subscription event trigger time
   * @return eventTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-06-20T15:04:58.424730Z", value = "Webhook subscription event trigger time")

  public OffsetDateTime getEventTime() {
    return eventTime;
  }


  public void setEventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookEventDetailsResponse webhookEventDetailsResponse = (WebhookEventDetailsResponse) o;
    return Objects.equals(this.uuid, webhookEventDetailsResponse.uuid) &&
        Objects.equals(this.name, webhookEventDetailsResponse.name) &&
        Objects.equals(this.type, webhookEventDetailsResponse.type) &&
        Objects.equals(this.httpStatusCode, webhookEventDetailsResponse.httpStatusCode) &&
        Objects.equals(this.error, webhookEventDetailsResponse.error) &&
        Objects.equals(this.deliveryTime, webhookEventDetailsResponse.deliveryTime) &&
        Objects.equals(this.url, webhookEventDetailsResponse.url) &&
        Objects.equals(this.signature, webhookEventDetailsResponse.signature) &&
        Objects.equals(this.requestBody, webhookEventDetailsResponse.requestBody) &&
        Objects.equals(this.responseBody, webhookEventDetailsResponse.responseBody) &&
        Objects.equals(this.responseHeaders, webhookEventDetailsResponse.responseHeaders) &&
        Objects.equals(this.eventTime, webhookEventDetailsResponse.eventTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, name, type, httpStatusCode, error, deliveryTime, url, signature, requestBody, responseBody, responseHeaders, eventTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookEventDetailsResponse {\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    httpStatusCode: ").append(toIndentedString(httpStatusCode)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    deliveryTime: ").append(toIndentedString(deliveryTime)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    requestBody: ").append(toIndentedString(requestBody)).append("\n");
    sb.append("    responseBody: ").append(toIndentedString(responseBody)).append("\n");
    sb.append("    responseHeaders: ").append(toIndentedString(responseHeaders)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

